/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List achievements */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.achievementDTO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an achievement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Achievement */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertAchievementRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.achievementDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/achievements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an achievement */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Achievement ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an achievement */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Achievement ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Achievement */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertAchievementRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.achievementDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all announcements for admin management (includes drafts) */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.announcementDTO"][];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin dashboard summary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all events for admin management (includes private events) */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.eventDTO"][];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all training schedules for admin management (includes inactive) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.trainingScheduleDTO"][];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public announcements */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.announcementDTO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an announcement
         * @description Omit published_at (or send null) to save as a draft.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Announcement */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertAnnouncementRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.announcementDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements/internal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List announcements including members-only ones */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.announcementDTO"][];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an announcement */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Announcement ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an announcement */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Announcement ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Announcement */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertAnnouncementRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.announcementDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current community */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.communityDTO"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public events */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                    /** @description Filter start_at >= (RFC3339) */
                    from?: string;
                    /** @description Filter start_at <= (RFC3339) */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.eventDTO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Event */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertEventRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.eventDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a public event
         * @description Private events are hidden from anonymous callers (returned as 404).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.eventDTO"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete an event (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an event */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Event */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertEventRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.eventDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/events/{id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** RSVP to an event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description RSVP status */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.rsvpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gallery items */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                    /** @description Filter by event ID */
                    event_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.galleryItemDTO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Save gallery item metadata after a successful upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Gallery item */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.createGalleryItemRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.galleryItemDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallery/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a presigned R2 upload URL
         * @description Validates content type and size before issuing a short-lived presigned PUT URL.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Upload metadata */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.presignUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallery/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a gallery item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Gallery item ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                    /** @description Filter by role */
                    role?: "member" | "officer" | "admin";
                    /** @description Filter by status */
                    status?: "active" | "inactive" | "banned";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.membershipDTO"][];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a member's role */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Membership ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description New role */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.updateMembershipRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.membershipDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/membership-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List membership applications */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                    /** @description Filter by status */
                    status?: "pending" | "approved" | "rejected";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.membershipApplicationDTO"][];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Submit a membership application
         * @description Public, rate-limited endpoint for the "join us" form.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Application */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.submitMembershipApplicationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.membershipApplicationDTO"];
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/membership-applications/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve a membership application
         * @description Auto-creates the membership if the applicant already has a synced user; otherwise deferred until they sign up.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Application ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.membershipApplicationDTO"];
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/membership-applications/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a membership application */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Application ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.membershipApplicationDTO"];
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active training schedules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.trainingScheduleDTO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a training schedule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Schedule */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertTrainingScheduleRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.trainingScheduleDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a training schedule */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Schedule ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a training schedule */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Schedule ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Schedule */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["handler.upsertTrainingScheduleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.trainingScheduleDTO"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.userDTO"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clerk user.created/user.updated webhook
         * @description Public but signature-verified (Svix headers). Upserts the local user row — see docs/Schema.md §2.2.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"] & {
                            data?: components["schemas"]["handler.userDTO"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "handler.achievementDTO": {
            achieved_at?: string | null;
            community_id?: string | null;
            description?: string | null;
            icon_or_badge_url?: string | null;
            id?: string | null;
            member_id?: string | null;
            title?: string | null;
        };
        "handler.announcementDTO": {
            community_id?: string | null;
            content?: string | null;
            created_at?: string | null;
            created_by?: string | null;
            id?: string | null;
            published_at?: string | null;
            title?: string | null;
            urgency?: string | null;
            visibility?: string | null;
        };
        "handler.communityDTO": {
            cover_image_url?: string | null;
            created_at?: string | null;
            description?: string | null;
            id?: string | null;
            logo_url?: string | null;
            name?: string | null;
            primary_color?: string | null;
            slug?: string | null;
            tagline?: string | null;
            updated_at?: string | null;
        };
        "handler.createGalleryItemRequest": {
            caption?: string | null;
            event_id?: string | null;
            media_url: string;
            thumbnail_url?: string | null;
            type: string;
        };
        "handler.eventDTO": {
            category?: string | null;
            community_id?: string | null;
            cover_image_url?: string | null;
            created_at?: string | null;
            created_by?: string | null;
            description?: string | null;
            end_at?: string | null;
            id?: string | null;
            is_public?: boolean | null;
            location?: string | null;
            start_at?: string | null;
            title?: string | null;
            updated_at?: string | null;
        };
        "handler.galleryItemDTO": {
            caption?: string | null;
            community_id?: string | null;
            created_at?: string | null;
            event_id?: string | null;
            id?: string | null;
            media_url?: string | null;
            thumbnail_url?: string | null;
            type?: string | null;
            uploaded_by?: string | null;
        };
        "handler.membershipApplicationDTO": {
            community_id?: string | null;
            created_at?: string | null;
            email?: string | null;
            full_name?: string | null;
            id?: string | null;
            motivation?: string | null;
            phone?: string | null;
            reviewed_at?: string | null;
            reviewed_by?: string | null;
            status?: string | null;
        };
        "handler.membershipDTO": {
            bio?: string | null;
            community_id?: string | null;
            id?: string | null;
            joined_at?: string | null;
            role?: string | null;
            status?: string | null;
            user_id?: string | null;
        };
        "handler.presignUploadRequest": {
            content_type: string;
            size_bytes: number;
        };
        "handler.rsvpRequest": {
            status: string;
        };
        "handler.submitMembershipApplicationRequest": {
            email: string;
            full_name: string;
            motivation?: string | null;
            phone: string;
        };
        "handler.trainingScheduleDTO": {
            community_id?: string | null;
            day_of_week?: number | null;
            end_time?: string | null;
            id?: string | null;
            is_active?: boolean | null;
            location?: string | null;
            start_time?: string | null;
            title?: string | null;
        };
        "handler.updateMembershipRoleRequest": {
            role: string;
        };
        "handler.upsertAchievementRequest": {
            achieved_at: string;
            description?: string | null;
            icon_or_badge_url?: string | null;
            member_id?: string | null;
            title: string;
        };
        "handler.upsertAnnouncementRequest": {
            content: string;
            published_at?: string | null;
            title: string;
            urgency: string;
            visibility: string;
        };
        "handler.upsertEventRequest": {
            category: string;
            cover_image_url?: string | null;
            description?: string | null;
            end_at: string;
            is_public?: boolean | null;
            location?: string | null;
            start_at: string;
            title: string;
        };
        "handler.upsertTrainingScheduleRequest": {
            day_of_week?: number | null;
            end_time: string;
            is_active?: boolean | null;
            location?: string | null;
            start_time: string;
            title: string;
        };
        "handler.userDTO": {
            avatar_url?: string | null;
            created_at?: string | null;
            email?: string | null;
            full_name?: string | null;
            id?: string | null;
            phone?: string | null;
            updated_at?: string | null;
        };
        "response.Envelope": {
            data?: unknown;
            error?: components["schemas"]["response.ErrorBody"];
            meta?: components["schemas"]["response.Meta"];
            success?: boolean | null;
        };
        "response.ErrorBody": {
            code?: components["schemas"]["response.ErrorCode"];
            fields?: {
                [key: string]: string;
            } | null;
            message?: string | null;
        } | null;
        /** @enum {string|null} */
        "response.ErrorCode": "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL_ERROR" | null;
        "response.Meta": {
            page?: number | null;
            per_page?: number | null;
            total?: number | null;
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
